package org.example.stocksteps.companydetail

object MetricEducation {
    private val metrics = listOf(
        FinancialMetric("marketCap", "Market cap", "The total market value of a company's shares. It measures company size, not whether a stock is a good investment.", "money"),
        FinancialMetric("pe", "P/E", "How much investors pay for each dollar of earnings. Compare with the company's history, industry and growth. P/E may not be meaningful when earnings are zero or negative."),
        FinancialMetric("forwardPe", "Forward P/E", "Price compared with estimated future earnings. Forecasts can change and may be wrong."),
        FinancialMetric("revenueGrowth", "Revenue growth", "How much sales changed from the comparable prior period. Growth in sales does not necessarily mean growth in profit.", "percent"),
        FinancialMetric("epsGrowth", "EPS growth", "How much earnings per share changed from the comparable prior period. Share count changes can also affect EPS.", "percent"),
        FinancialMetric("roic", "ROIC", "Return on invested capital compares operating profit with the capital used by the business. Definitions vary; industry comparisons need consistent methods.", "percent"),
        FinancialMetric("revenue", "Revenue", "Money earned from selling products and services, before expenses.", "money"),
        FinancialMetric("netIncome", "Net income", "Profit remaining after costs, interest and taxes. A negative number means a loss.", "money"),
        FinancialMetric("eps", "EPS", "Earnings divided by the number of shares. It describes profit attributable to each share."),
        FinancialMetric("grossMargin", "Gross margin", "The share of sales left after the direct cost of products or services.", "percent"),
        FinancialMetric("operatingMargin", "Operating margin", "The share of sales left after operating expenses, before interest and taxes.", "percent"),
        FinancialMetric("netMargin", "Net margin", "The percentage of sales left as profit after all expenses.", "percent"),
        FinancialMetric("roe", "ROE", "Return on equity compares profit with shareholder equity. High debt or very small equity can distort the ratio.", "percent"),
        FinancialMetric("cash", "Cash", "Cash and cash equivalents available to the company. Cash must be considered alongside debt and operating needs.", "money"),
        FinancialMetric("debt", "Total debt", "Borrowed money the company must repay. Debt is not automatically harmful; repayment costs and cash generation matter.", "money"),
        FinancialMetric("debtEquity", "Debt / equity", "Debt compared with shareholder equity. It can be difficult to interpret when equity is small or negative."),
        FinancialMetric("interestCoverage", "Interest coverage", "How many times operating earnings cover interest costs. Missing or zero interest expense needs special treatment."),
        FinancialMetric("operatingCashFlow", "Operating cash flow", "Cash generated by everyday business operations. Accounting profit and actual cash flow can differ.", "money"),
        FinancialMetric("capex", "Capital expenditure", "Cash invested in equipment, property and other assets needed to operate and grow.", "money"),
        FinancialMetric("freeCashFlow", "Free cash flow", "Cash remaining after operating cash flow pays for capital expenditure. It can be used for debt, dividends or reinvestment.", "money"),
        FinancialMetric("dividendYield", "Dividend yield", "Annual dividends relative to the share price. Dividends can change, and a high yield does not guarantee a safe payout.", "percent"),
        FinancialMetric("dividendGrowth", "Dividend growth", "The change in dividends across comparable periods. Past increases do not guarantee future payments.", "percent"),
        FinancialMetric("buybacks", "Share buybacks", "Money spent repurchasing shares. Buybacks can reduce share count but are not always beneficial, especially when financed with debt or at high prices.", "money"),
        FinancialMetric("shares", "Shares outstanding", "The number of shares currently held by investors. More shares can dilute each shareholder's ownership; fewer can increase it.", "count"),
        FinancialMetric("revenueCagr3", "Revenue 3Y CAGR", "Annualized revenue growth over three fiscal years. Positive beginning and ending values are required.", "percent"),
        FinancialMetric("revenueCagr5", "Revenue 5Y CAGR", "Annualized revenue growth over five fiscal years. Missing history stays unavailable.", "percent"),
        FinancialMetric("netIncomeGrowth", "Net income growth", "Year-over-year profit change. Comparisons across losses require care.", "percent"),
        FinancialMetric("epsCagr3", "Diluted EPS 3Y CAGR", "Annualized diluted earnings-per-share growth over three fiscal years.", "percent"),
        FinancialMetric("epsCagr5", "Diluted EPS 5Y CAGR", "Annualized diluted earnings-per-share growth over five fiscal years.", "percent"),
        FinancialMetric("roa", "ROA", "Profit relative to assets used by the company.", "percent"),
        FinancialMetric("assets", "Total assets", "Resources recorded on the balance sheet.", "money"),
        FinancialMetric("liabilities", "Total liabilities", "Recorded obligations, including obligations other than borrowing.", "money"),
        FinancialMetric("equity", "Shareholder equity", "Assets remaining after liabilities; it can be negative.", "money"),
        FinancialMetric("currentRatio", "Current ratio", "Current assets relative to current liabilities."),
        FinancialMetric("quickRatio", "Quick ratio", "Liquid current assets relative to current liabilities."),
        FinancialMetric("fcfMargin", "FCF margin", "Free cash flow as a percentage of revenue in the same period.", "percent"),
        FinancialMetric("dividendPerShare", "Dividend per share", "Total dividends per share over the trailing year."),
        FinancialMetric("payoutRatio", "Payout ratio", "Dividends relative to earnings; unsuitable when earnings are non-positive.", "percent"),
        FinancialMetric("sharesChange5", "Shares change over 5Y", "Historical share counts must use a consistent split-adjusted basis.", "percent"),
        FinancialMetric("priceBook", "Price / book", "Market value relative to shareholder equity; unsuitable with non-positive equity."),
        FinancialMetric("enterpriseValue", "Enterprise value", "Provider enterprise value, including debt and cash adjustments.", "money"),
        FinancialMetric("peg", "PEG", "P/E relative to expected earnings growth. Forecasts and calculation methods can make comparisons unreliable."),
        FinancialMetric("priceSales", "Price / sales", "Company market value relative to revenue. It does not account for how much of sales becomes profit."),
        FinancialMetric("priceFcf", "Price / free cash flow", "Company market value relative to free cash flow. It may not be meaningful when free cash flow is negative."),
        FinancialMetric("evEbitda", "EV / EBITDA", "Enterprise value relative to earnings before interest, tax, depreciation and amortization. This measure leaves out important cash costs.")
    ).associateBy { it.id }
    fun metric(id: String): FinancialMetric = requireNotNull(metrics[id])
    fun financialSections(): List<FinancialSection> = listOf(
        section("Growth", "revenue", "revenueGrowth", "revenueCagr3", "revenueCagr5", "netIncome", "netIncomeGrowth", "eps", "epsGrowth", "epsCagr3", "epsCagr5"),
        section("Profitability", "grossMargin", "operatingMargin", "netMargin", "roe", "roa", "roic"),
        section("Financial health", "cash", "debt", "assets", "liabilities", "equity", "debtEquity", "currentRatio", "quickRatio", "interestCoverage"),
        section("Cash flow", "operatingCashFlow", "capex", "freeCashFlow", "fcfMargin").copy(explanation = "Operating cash flow − capital expenditure = free cash flow. No conclusion is shown without the underlying amounts."),
        section("Shareholders", "dividendYield", "dividendPerShare", "dividendGrowth", "payoutRatio", "buybacks", "shares", "sharesChange5")
    )
    private fun section(title: String, vararg ids: String) = FinancialSection(title, ids.map(::metric))
}
