package org.example.stocksteps.companydetail

object MetricEducation {
    private val metrics by lazy { listOf(
        FinancialMetric("marketCap", "Market cap", "The total market value of a company's shares. It measures company size, not whether a stock is a good investment.", "money"),
        FinancialMetric("pe", "P/E", "How much investors pay for each dollar of earnings. Compare with the company's history, industry and growth. P/E may not be meaningful when earnings are zero or negative."),
        FinancialMetric("forwardPe", "Forward P/E", "Price compared with estimated future earnings. Forecasts can change and may be wrong."),
        FinancialMetric("revenueGrowth", "Revenue growth", "How much sales changed from the comparable prior period. Growth in sales does not necessarily mean growth in profit.", "percent"),
        FinancialMetric("quarterRevenueGrowth", "Quarterly revenue growth", "How much sales in the latest reported quarter changed compared with the same quarter a year earlier. Comparing the same quarter helps account for seasonal patterns, such as holiday sales.", "percent"),
        FinancialMetric("epsGrowth", "EPS growth", "How much earnings per share changed from the comparable prior period. Share count changes can also affect EPS.", "percent"),
        FinancialMetric("roic", "ROIC", "Return on invested capital compares operating profit with the capital used by the business. Definitions vary; industry comparisons need consistent methods.", "percent"),
        FinancialMetric("revenue", "Revenue", "Money earned from selling products and services, before expenses.", "money"),
        FinancialMetric("netIncome", "Net income", "Profit remaining after costs, interest and taxes. A negative number means a loss.", "money"),
        FinancialMetric("eps", "EPS", "Earnings divided by the number of shares. It describes profit attributable to each share."),
        FinancialMetric("grossMargin", "Gross margin", "The share of sales left after the direct cost of products or services.", "percent"),
        FinancialMetric("operatingMargin", "Operating margin", "The share of sales left after operating expenses, before interest and taxes.", "percent"),
        FinancialMetric("netMargin", "Net margin", "The percentage of sales left as profit after all expenses.", "percent"),
        FinancialMetric("roe", "ROE", "Return on equity compares profit with shareholder equity. High debt or very small equity can distort the ratio.", "percent"),
        FinancialMetric("cash", "Cash", "Cash and cash equivalents available to the company. Cash must be considered alongside debt and operating needs.", "money"),
        FinancialMetric("debt", "Total debt", "Borrowed money the company must repay. Debt is not automatically harmful; repayment costs and cash generation matter.", "money"),
        FinancialMetric("debtEquity", "Debt / equity", "Debt compared with shareholder equity. It can be difficult to interpret when equity is small or negative."),
        FinancialMetric("interestCoverage", "Interest coverage", "How many times operating earnings cover interest costs. Missing or zero interest expense needs special treatment."),
        FinancialMetric("operatingCashFlow", "Operating cash flow", "Cash generated by everyday business operations. Accounting profit and actual cash flow can differ.", "money"),
        FinancialMetric("capex", "Capital expenditure", "Cash invested in equipment, property and other assets needed to operate and grow.", "money"),
        FinancialMetric("freeCashFlow", "Free cash flow", "Cash remaining after operating cash flow pays for capital expenditure. It can be used for debt, dividends or reinvestment.", "money"),
        FinancialMetric("dividendYield", "Dividend yield", "Annual dividends relative to the share price. Dividends can change, and a high yield does not guarantee a safe payout.", "percent"),
        FinancialMetric("dividendGrowth", "Dividend growth", "The change in dividends across comparable periods. Past increases do not guarantee future payments.", "percent"),
        FinancialMetric("buybacks", "Share buybacks", "Money spent repurchasing shares. Buybacks can reduce share count but are not always beneficial, especially when financed with debt or at high prices.", "money"),
        FinancialMetric("shares", "Shares outstanding", "The number of shares currently held by investors. More shares can dilute each shareholder's ownership; fewer can increase it.", "count"),
        FinancialMetric("revenueCagr3", "Revenue 3Y CAGR", "Annualized revenue growth over three fiscal years. Positive beginning and ending values are required.", "percent"),
        FinancialMetric("revenueCagr5", "Revenue 5Y CAGR", "Annualized revenue growth over five fiscal years. Missing history stays unavailable.", "percent"),
        FinancialMetric("netIncomeGrowth", "Net income growth", "Year-over-year profit change. Comparisons across losses require care.", "percent"),
        FinancialMetric("epsCagr3", "Diluted EPS 3Y CAGR", "Annualized diluted earnings-per-share growth over three fiscal years.", "percent"),
        FinancialMetric("epsCagr5", "Diluted EPS 5Y CAGR", "Annualized diluted earnings-per-share growth over five fiscal years.", "percent"),
        FinancialMetric("roa", "ROA", "Profit relative to assets used by the company.", "percent"),
        FinancialMetric("assets", "Total assets", "Resources recorded on the balance sheet.", "money"),
        FinancialMetric("liabilities", "Total liabilities", "Recorded obligations, including obligations other than borrowing.", "money"),
        FinancialMetric("equity", "Shareholder equity", "Assets remaining after liabilities; it can be negative.", "money"),
        FinancialMetric("currentRatio", "Current ratio", "Current assets relative to current liabilities."),
        FinancialMetric("quickRatio", "Quick ratio", "Liquid current assets relative to current liabilities."),
        FinancialMetric("fcfMargin", "FCF margin", "Free cash flow as a percentage of revenue in the same period.", "percent"),
        FinancialMetric("dividendPerShare", "Dividend per share", "Total dividends per share over the trailing year."),
        FinancialMetric("payoutRatio", "Payout ratio", "Dividends relative to earnings; unsuitable when earnings are non-positive.", "percent"),
        FinancialMetric("sharesChange5", "Shares change over 5Y", "Historical share counts must use a consistent split-adjusted basis.", "percent"),
        FinancialMetric("priceBook", "Price / book", "Market value relative to shareholder equity; unsuitable with non-positive equity."),
        FinancialMetric("enterpriseValue", "Enterprise value", "Provider enterprise value, including debt and cash adjustments.", "money"),
        FinancialMetric("peg", "PEG", "P/E relative to expected earnings growth. Forecasts and calculation methods can make comparisons unreliable."),
        FinancialMetric("priceSales", "Price / sales", "Company market value relative to revenue. It does not account for how much of sales becomes profit."),
        FinancialMetric("priceFcf", "Price / free cash flow", "Company market value relative to free cash flow. It may not be meaningful when free cash flow is negative."),
        FinancialMetric("evEbitda", "EV / EBITDA", "Enterprise value relative to earnings before interest, tax, depreciation and amortization. This measure leaves out important cash costs."),
        FinancialMetric("fcfGrowth", "Free cash flow growth", "How much free cash flow changed from the prior fiscal year. Not shown when the prior year's free cash flow was zero or negative.", "percent"),
        FinancialMetric("yearRangePosition", "52-week range position", "Where today's price sits between its 52-week low (0%) and high (100%). It describes recent price movement, not value.", "percent"),
        FinancialMetric("price", "Share price", "The latest trading price of one share. A higher share price doesn't mean a company is bigger or better.", "money"),
        FinancialMetric("volume", "Trading volume", "How many shares traded in the latest session. Low volume can mean prices move more on small trades.", "count")
    ).map { it.copy(calculation = CALCULATIONS[it.id]?.first, why = CALCULATIONS[it.id]?.second) }.associateBy { it.id } }

    /** How each metric is calculated and why investors look at it (shown in metric info sheets). */
    private val CALCULATIONS = mapOf(
        "marketCap" to ("Share price × shares outstanding." to "Shows company size, which affects how a business is compared with peers."),
        "pe" to ("Share price ÷ diluted earnings per share over the trailing twelve months. Not shown when those earnings are zero or negative (a loss)." to "Shows how much investors pay for current earnings."),
        "forwardPe" to ("Share price ÷ analysts' average EPS estimate for the next fiscal year." to "Shows price relative to expected, not reported, earnings."),
        "priceSales" to ("Market cap ÷ revenue over the trailing twelve months." to "Useful when earnings are small or negative."),
        "priceBook" to ("Market cap ÷ shareholder equity." to "Often used for asset-heavy businesses such as banks."),
        "evEbitda" to ("(Market cap + debt − cash) ÷ EBITDA." to "Compares companies with different amounts of debt."),
        "revenueGrowth" to ("(This fiscal year's revenue − last year's) ÷ last year's revenue." to "Shows whether sales are expanding or shrinking."),
        "quarterRevenueGrowth" to ("(Latest quarter's revenue − the same fiscal quarter a year earlier) ÷ that earlier quarter's revenue." to "A more recent view of sales than the fiscal year, without mixing in seasonal swings."),
        "epsGrowth" to ("(This year's diluted EPS − last year's) ÷ last year's EPS, only when last year's EPS was positive." to "Shows how profit per share changed."),
        "netIncomeGrowth" to ("(This year's net income − last year's) ÷ last year's, only when last year was profitable." to "Shows how total profit changed."),
        "fcfGrowth" to ("(This year's free cash flow − last year's) ÷ last year's, when last year's was positive and in the same currency." to "Cash generation can differ from accounting profit."),
        "grossMargin" to ("Gross profit ÷ revenue." to "Shows how much each sale earns before overhead costs."),
        "operatingMargin" to ("Operating income ÷ revenue." to "Shows profitability from the core business."),
        "netMargin" to ("Net income ÷ revenue over the same period (trailing twelve months, or the latest fiscal year when that's all the source provides; the row says which)." to "Shows how much of each dollar of sales becomes profit."),
        "roe" to ("Net income ÷ shareholder equity." to "Shows profit generated with shareholders' money."),
        "roic" to ("Operating profit after tax ÷ invested capital (provider definition)." to "Shows how efficiently a business uses all its capital."),
        "debtEquity" to ("Total debt ÷ total shareholder equity, from the latest reported balance sheet (provider ratio when available). Not shown when equity is zero or negative." to "Shows how much a company relies on borrowing."),
        "currentRatio" to ("Current assets ÷ current liabilities." to "Shows ability to cover bills due within a year."),
        "interestCoverage" to ("Operating income ÷ interest expense." to "Shows how comfortably earnings cover interest."),
        "freeCashFlow" to ("Operating cash flow − capital expenditure." to "Cash available for dividends, debt repayment or reinvestment."),
        "operatingCashFlow" to ("Cash from day-to-day operations in the fiscal year." to "Shows whether the business generates cash."),
        "cash" to ("Cash and cash equivalents on the latest balance sheet." to "A cushion for expenses and investment."),
        "debt" to ("Short- and long-term borrowings on the latest balance sheet." to "Debt must be repaid and carries interest costs."),
        "dividendYield" to ("Dividends per share paid over the trailing year ÷ current share price. It describes past payments, not guaranteed future income." to "Shows the cash income paid relative to the price."),
        "payoutRatio" to ("Dividends paid ÷ net income." to "Shows how much profit is paid out instead of reinvested."),
        "dividendGrowth" to ("Change in total dividends between the last two calendar years." to "Shows whether payments have been rising or falling."),
        "yearRangePosition" to ("(Price − 52-week low) ÷ (52-week high − 52-week low)." to "Gives context for recent price moves.")
    )

    fun metric(id: String): FinancialMetric = requireNotNull(metrics[id])
    /** Null for ids without beginner education (callers show the metric's own description instead). */
    fun find(id: String): FinancialMetric? = metrics[id]
    fun financialSections(): List<FinancialSection> = listOf(
        section("Growth", "revenue", "revenueGrowth", "revenueCagr3", "revenueCagr5", "netIncome", "netIncomeGrowth", "eps", "epsGrowth", "epsCagr3", "epsCagr5"),
        section("Profitability", "grossMargin", "operatingMargin", "netMargin", "roe", "roa", "roic"),
        section("Financial health", "cash", "debt", "assets", "liabilities", "equity", "debtEquity", "currentRatio", "quickRatio", "interestCoverage"),
        section("Cash flow", "operatingCashFlow", "capex", "freeCashFlow", "fcfMargin").copy(explanation = "Operating cash flow − capital expenditure = free cash flow. No conclusion is shown without the underlying amounts."),
        section("Shareholders", "dividendYield", "dividendPerShare", "dividendGrowth", "payoutRatio", "buybacks", "shares", "sharesChange5")
    )
    private fun section(title: String, vararg ids: String) = FinancialSection(title, ids.map(::metric))
}
