package org.example.stocksteps.earnings

import io.ktor.client.HttpClient
import io.ktor.client.request.header
import io.ktor.client.request.parameter
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.*
import org.example.stocksteps.httpclient.apiCall
import org.example.stocksteps.model.EarningsDateStatus
import org.example.stocksteps.model.EarningsTime
import java.time.LocalDate

/** Normalized earnings events from one provider (never mixed per event). */
interface EarningsDataSource {
    /** Events (upcoming and reported) whose announcement date is within [from]..[to]. */
    suspend fun calendar(from: LocalDate, to: LocalDate): List<EarningsEvent>
    /** Every known event for [symbol] (reported history and the next one), any order. */
    suspend fun history(symbol: String): List<EarningsEvent>
    val label: String
}

/** MOCK: `fixtures/earnings/events.json` (generated by scripts/generate_earnings_fixtures.py). No network. */
class FixtureEarningsDataSource : EarningsDataSource {
    override val label = "StockSteps sample fixtures"
    private val events: List<EarningsEvent> by lazy {
        val text = requireNotNull(javaClass.classLoader.getResource("fixtures/earnings/events.json")) { "Missing earnings fixture" }.readText()
        Json { ignoreUnknownKeys = true }.decodeFromString(ListSerializer(EarningsEvent.serializer()), text)
    }
    override suspend fun calendar(from: LocalDate, to: LocalDate) = events.filter { it.date >= from.toString() && it.date <= to.toString() }
    override suspend fun history(symbol: String) = events.filter { it.symbol.equals(symbol, ignoreCase = true) }
}

/**
 * REAL: Finnhub's earnings calendar (`/calendar/earnings`). One provider supplies date, session
 * (bmo/amc/dmh), fiscal quarter/year, EPS and revenue estimates and actuals for each event, so
 * actuals and estimates are never combined across providers. Finnhub reports actual EPS on the
 * same basis analysts estimate (typically adjusted), so both sides are labelled ADJUSTED; it
 * doesn't say whether a date is company-confirmed, so dates are ESTIMATED until reported.
 */
class FinnhubEarningsDataSource(private val client: HttpClient, private val apiKey: String, private val historyYears: Long = 3) : EarningsDataSource {
    override val label = "Finnhub earnings calendar"

    private suspend fun fetch(from: LocalDate, to: LocalDate, symbol: String? = null): List<EarningsEvent> {
        val response = client.apiCall<JsonObject>("https://finnhub.io/api/v1/calendar/earnings") {
            header("X-Finnhub-Token", apiKey)
            parameter("from", from.toString()); parameter("to", to.toString())
            symbol?.let { parameter("symbol", it) }
        }
        return response["earningsCalendar"]?.jsonArray.orEmpty().mapNotNull { (it as? JsonObject)?.let(EarningsNormalizer::finnhub) }
    }

    override suspend fun calendar(from: LocalDate, to: LocalDate) = fetch(from, to)
    override suspend fun history(symbol: String): List<EarningsEvent> {
        val today = LocalDate.now()
        return fetch(today.minusYears(historyYears), today.plusDays(120), symbol)
    }
}

object EarningsNormalizer {
    private fun JsonObject.text(key: String) = this[key]?.jsonPrimitive?.contentOrNull?.takeIf { it.isNotBlank() }
    private fun JsonObject.number(key: String) = this[key]?.jsonPrimitive?.doubleOrNull?.takeIf { it.isFinite() }

    fun session(hint: String?): EarningsTime = when (hint?.lowercase()) {
        "bmo" -> EarningsTime.BEFORE_OPEN
        "amc" -> EarningsTime.AFTER_CLOSE
        "dmh" -> EarningsTime.DURING_MARKET
        else -> EarningsTime.UNKNOWN // never inferred from a timestamp
    }

    /** One Finnhub calendar row → event; null when identity fields are missing. */
    fun finnhub(row: JsonObject): EarningsEvent? {
        val symbol = row.text("symbol")?.uppercase() ?: return null
        val date = row.text("date")?.takeIf { runCatching { LocalDate.parse(it) }.isSuccess } ?: return null
        val year = row.number("year")?.toInt() ?: return null
        val quarter = row.number("quarter")?.toInt()?.takeIf { it in 1..4 } ?: return null
        val source = "Finnhub earnings calendar"
        val estimate = EarningsEstimate(row.number("epsEstimate"), EpsBasis.ADJUSTED, row.number("revenueEstimate"), null, null, source)
            .takeIf { it.eps != null || it.revenue != null }
        val actual = EarningsActual(row.number("epsActual"), EpsBasis.ADJUSTED, row.number("revenueActual"), null, source)
            .takeIf { it.eps != null || it.revenue != null }
        return EarningsEvent(
            id = "$symbol:$year-Q$quarter", symbol = symbol, name = symbol, fiscalYear = year, fiscalQuarter = quarter,
            date = date, session = session(row.text("hour")),
            dateStatus = if (actual != null) EarningsDateStatus.CONFIRMED else EarningsDateStatus.ESTIMATED,
            estimate = estimate, actual = actual, source = source, updatedAt = java.time.Instant.now().toString()
        )
    }
}
